# Pull base image.

FROM nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

# Install.
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y build-essential git cmake g++ gcc wget unzip libeigen3-dev libsleef-dev
RUN wget https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcu113.zip
RUN unzip -a libtorch-cxx11-abi-shared-with-deps-1.10.0+cu113.zip && rm libtorch-cxx11-abi-shared-with-deps-1.10.0+cu113.zip && \
    cd libtorch && \
    cp -r ./* /usr/local/ && \
    cd / && rm -rf /libtorch
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin \
    mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub \
    add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /" \
    apt-get update \
    apt-get -y install cuda

